### ISSUE TITLE
Spy breaks when upgrading react-redux to 7.x.x

### ISSUE THREAD

**Issue by achasveachas** [reid47/react-spy-on-render#1]
The Davos team is trying to update our dependencies.

One of the dependencies we're trying to upgrade is react-redux which we currently have at 6.0.1.

When we try upgrading to any version =< 7.0.0 any test we have that uses `spyOnRender` breaks with the following error:

```
Failures: 
1) NoticeList New Pivotal Notice form when the new notice button is clicked opens the modal
1.1) Error: <spyOn> : could not find an object to spy upon for render()
Usage: spyOn(<object>, <methodName>)
    Error: <spyOn> : could not find an object to spy upon for render()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at spyOnRender (http://localhost:8000/webpack:/node_modules/pivotal-js-react-test-helpers/lib/index.js:115:1)
        at UserContext.<anonymous> (http://localhost:8000/webpack:/spec/src/components/NoticeList.test.js:137:1)
        at <Jasmine>
1.2) Error: <toHaveBeenCalled> : Expected a spy, but got undefined.
Usage: expect(<spyObj>).toHaveBeenCalled()
    Error: <toHaveBeenCalled> : Expected a spy, but got undefined.
    Usage: expect(<spyObj>).toHaveBeenCalled()
        at <Jasmine>
        at UserContext.<anonymous> (http://localhost:8000/webpack:/spec/src/components/NoticeList.test.js:509:1)
        at <Jasmine>
```

**Comment by reidmit** [comment]
Hi @achasveachas ! Thanks for the report. Unfortunately, I may not have time to dig into this soon – would you be open to submitting a PR?

**Comment by achasveachas** [comment]
Hi @reid47,

For now we put this story a little further back in our backlog while we take care of more pressing matters. If it isn't fixed by the time we get back to it we'll be happy to look into it and maybe submit a PR if we find a fix.
